// Generated by `bun init`
declare module "*.css";
declare module "*.svg" {
  /**
   * A path to the SVG file
   */
  const path: `${string}.svg`;
  export = path;
}

declare module "*.module.css" {
  /**
   * A record of class names to their corresponding CSS module classes
   */
  const classes: { readonly [key: string]: string };
  export = classes;
}

// Environment variables
declare global {
  interface ImportMetaEnv {
    readonly BUN_PUBLIC_BACKEND_URL?: string;
  }
}

export {};
